version: '3.7'
services:
    postgres:
        container_name: btp_project_postgres_db
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
          - POSTGRES_DB=dev
        ports:
          - '5432:5432'
        volumes: 
          - postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    pgadmin:
        container_name: btp_project_pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"
volumes:
  postgres-data: